import { TabulatorFull as Tabulator } from "tabulator-tables";

export function tabulatorTemplate() {
  return new Tabulator("", {
    initialSort: [
      { column: "column1", dir: "asc" },
      { column: "column2", dir: "desc" },
      { column: "column3", dir: "asc" },
    ],
    columns: [
      {
        sorterParams: {
          format: undefined,
          locale: undefined,
          alignEmptyValues: undefined,
          type: "sum",
        },
        formatterParams: undefined,
        editorParams: undefined,
        title: "Column Three",
        field: "column3",
        visible: undefined,
        width: undefined,
        hozAlign: "left",
        headerHozAlign: undefined,
        vertAlign: undefined,
        minWidth: undefined,
        widthGrow: undefined,
        widthShrink: undefined,
        resizable: undefined,
        frozen: undefined,
        responsive: undefined,
        tooltip: undefined,
        rowHandle: undefined,
        sorter: undefined,
        formatter: "color",
        variableHeight: undefined,
        editable: undefined,
        editor: undefined,
        validator: undefined,
        download: undefined,
        titleDownload: undefined,
        headerSort: undefined,
        headerSortStartingDir: undefined,
        headerSortTristate: undefined,
        headerTooltip: undefined,
        headerVertical: undefined,
        editableTitle: undefined,
        titleFormatter: undefined,
        headerFilter: undefined,
        headerFilterPlaceholder: undefined,
        headerFilterLiveFilter: undefined,
        htmlOutput: undefined,
        clipboard: undefined,
        print: undefined,
        titlePrint: undefined,
        maxWidth: undefined,
        headerWordWrap: undefined,
      },
      {
        sorterParams: {
          format: undefined,
          locale: undefined,
          alignEmptyValues: undefined,
          type: "sum",
        },
        formatterParams: {
          decimal: ",",
          thousand: ".",
          symbol: "\u20ac",
          symbolAfter: undefined,
          precision: undefined,
          negativeSign: undefined,
        },
        editorParams: {
          min: undefined,
          max: undefined,
          step: undefined,
          verticalNavigation: undefined,
          selectContents: undefined,
        },
        title: "Column Two",
        field: "column2",
        visible: undefined,
        width: undefined,
        hozAlign: "right",
        headerHozAlign: undefined,
        vertAlign: undefined,
        minWidth: undefined,
        widthGrow: undefined,
        widthShrink: undefined,
        resizable: undefined,
        frozen: undefined,
        responsive: undefined,
        tooltip: undefined,
        rowHandle: undefined,
        sorter: undefined,
        formatter: "money",
        variableHeight: undefined,
        editable: undefined,
        editor: undefined,
        validator: undefined,
        download: undefined,
        titleDownload: undefined,
        headerSort: undefined,
        headerSortStartingDir: undefined,
        headerSortTristate: undefined,
        headerTooltip: undefined,
        headerVertical: undefined,
        editableTitle: undefined,
        titleFormatter: undefined,
        headerFilter: undefined,
        headerFilterPlaceholder: undefined,
        headerFilterLiveFilter: undefined,
        htmlOutput: undefined,
        clipboard: undefined,
        print: undefined,
        titlePrint: undefined,
        maxWidth: undefined,
        headerWordWrap: undefined,
      },
      {
        sorterParams: {
          format: undefined,
          locale: undefined,
          alignEmptyValues: undefined,
          type: "min",
        },
        formatterParams: {
          allowEmpty: true,
          allowTruthy: undefined,
          tickElement: undefined,
          crossElement: undefined,
        },
        editorParams: {
          min: undefined,
          max: undefined,
          step: undefined,
          verticalNavigation: undefined,
          selectContents: undefined,
        },
        title: "Column One",
        field: "column1",
        visible: undefined,
        width: undefined,
        hozAlign: "center",
        headerHozAlign: undefined,
        vertAlign: undefined,
        minWidth: undefined,
        widthGrow: undefined,
        widthShrink: undefined,
        resizable: undefined,
        frozen: undefined,
        responsive: undefined,
        tooltip: undefined,
        rowHandle: undefined,
        sorter: undefined,
        formatter: "tickCross",
        variableHeight: undefined,
        editable: undefined,
        editor: undefined,
        validator: undefined,
        download: undefined,
        titleDownload: undefined,
        headerSort: undefined,
        headerSortStartingDir: undefined,
        headerSortTristate: undefined,
        headerTooltip: undefined,
        headerVertical: undefined,
        editableTitle: undefined,
        titleFormatter: undefined,
        headerFilter: undefined,
        headerFilterPlaceholder: undefined,
        headerFilterLiveFilter: undefined,
        htmlOutput: undefined,
        clipboard: undefined,
        print: undefined,
        titlePrint: undefined,
        maxWidth: undefined,
        headerWordWrap: undefined,
      },
    ],
    keybindings: {
      navPrev: undefined,
      navNext: undefined,
      navLeft: undefined,
      navRight: undefined,
      navUp: undefined,
      navDown: undefined,
      undo: undefined,
      redo: undefined,
      scrollPageUp: undefined,
      scrollPageDown: undefined,
      scrollToStart: undefined,
      scrollToEnd: undefined,
      copyToClipboard: undefined,
    },
    index: 1,
    data: undefined,
    importFormat: undefined,
    importReader: undefined,
    autoTables: null,
    ajaxURL: undefined,
    ajaxParams: undefined,
    ajaxContentType: undefined,
    ajaxFiltering: undefined,
    ajaxSorting: undefined,
    progressiveLoad: undefined,
    progressiveLoadDelay: undefined,
    progressiveLoadScrollMargin: undefined,
    ajaxLoader: undefined,
    ajaxLoaderLoading: undefined,
    ajaxLoaderError: undefined,
    dataLoader: null,
    dataLoaderError: null,
    dataLoaderErrorTimeout: null,
    sortMode: null,
    filterMode: null,
    pagination: null,
    paginationMode: null,
    paginationSize: undefined,
    paginationSizeSelector: undefined,
    paginationAddRow: undefined,
    paginationButtonCount: undefined,
    paginationInitialPage: undefined,
    sortOrderReverse: undefined,
    headerSortClickElement: null,
    autoColumns: undefined,
    layout: undefined,
    layoutColumnsOnNewData: undefined,
    responsiveLayout: undefined,
    responsiveLayoutCollapseStartOpen: undefined,
    responsiveLayoutCollapseUseFormatters: undefined,
    movableColumns: undefined,
    columnHeaderVertAlign: undefined,
    scrollToColumnPosition: undefined,
    scrollToColumnIfVisible: undefined,
    columnCalcs: undefined,
    nestedFieldSeparator: undefined,
    columnHeaderSortMulti: undefined,
    headerSort: undefined,
    resizableColumnFit: undefined,
    height: undefined,
    maxHeight: undefined,
    minHeight: undefined,
    renderVertical: undefined,
    renderHorizontal: undefined,
    rowHeight: null,
    renderVerticalBuffer: undefined,
    placeholder: null,
    placeholderHeaderFilter: null,
    footerElement: null,
    reactiveData: undefined,
    autoResize: undefined,
    invalidOptionWarnings: undefined,
    validationMode: undefined,
    textDirection: undefined,
  });
}
